.PHONY: build

GREEN = \033[0;32m
YELLOW = \033[0;33m
NO_COLOR = \033[0m

build:
	@echo "$(GREEN)Building the project...$(NO_COLOR)\n"
	bash build.sh
	@echo "\n$(YELLOW)Build completed!$(NO_COLOR)\n"

run:
	@echo "Running the program..."
	./progr
